apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::236453739001:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AS71MEVINV78
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::236453739001:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T08:21:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1671"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d8a12707-1076-425f-9142-591f5da39233
